### ISSUE TITLE
My driver's had this condition for a while

### ISSUE THREAD

**Issue by Clownacy** [Pokepunch/Nothing#1]
For some time, my driver's thread has opened with the following:

"To quote Irixion: "Do not reproduce [in part or in whole] without permission of creator, or I will hunt you down, and cut your penis off." This is your only warning."

**Comment by Pokepunch** [comment]
What? This is my hack, I used your driver but decided to switch Flamewing's S3K driver instead. Where am I reproducing part of your driver?

**Comment by Clownacy** [comment]
sound/S2Clone

**Comment by Pokepunch** [comment]
Oh sorry about that, I kept a backup while switching drivers and forgot to delete it afterwards.
